import { spawnSync } from "node:child_process";
import type { CodexProConfig } from "./config.js";
import type { Workspace } from "./guard.js";
import { CodexProError, PathGuard } from "./guard.js";
import type { OperationManager, OperationExecution } from "./operations/manager.js";
import { redactSensitiveText } from "./redact.js";
const SHA=/^[a-f0-9]{40,64}$/i, REF=/^[A-Za-z0-9][A-Za-z0-9._\/-]{0,199}$/;
function git(workspace:Workspace,args:string[],max:number){const r=spawnSync("git",args,{cwd:workspace.root,encoding:"utf8",maxBuffer:max,env:{...process.env,NO_COLOR:"1"}}); if(r.error||r.status!==0)throw new CodexProError(redactSensitiveText(r.error?.message||r.stderr?.trim()||r.stdout?.trim()||`git exited ${r.status}`)); return String(r.stdout??"").trim();}
function state(config:CodexProConfig,ws:Workspace){return {head:git(ws,["rev-parse","HEAD"],config.maxOutputBytes),branch:git(ws,["branch","--show-current"],config.maxOutputBytes)};}
function assertState(config:CodexProConfig,ws:Workspace,expectedHead:string,expectedBranch?:string){if(!SHA.test(expectedHead))throw new CodexProError("expected HEAD must be a full Git object id."); const s=state(config,ws); if(s.head.toLowerCase()!==expectedHead.toLowerCase())throw new CodexProError(`Git HEAD changed; expected ${expectedHead}, found ${s.head}.`); if(expectedBranch!==undefined&&s.branch!==expectedBranch)throw new CodexProError(`Git branch changed; expected ${expectedBranch}, found ${s.branch}.`); return s;}
function guardedPaths(guard:PathGuard,ws:Workspace,paths:string[]){if(!Array.isArray(paths)||paths.length===0)throw new CodexProError("git_stage requires explicit paths."); return [...new Set(paths.map(p=>guard.resolve(ws,p).relPath))];}
function staged(config:CodexProConfig,ws:Workspace){const out=git(ws,["diff","--cached","--name-only","--"],config.maxOutputBytes);return out?out.split(/\r?\n/).filter(Boolean):[];}
export async function gitStage(config:CodexProConfig,guard:PathGuard,ws:Workspace,ops:OperationManager,input:{paths:string[];expectedHead:string;idempotencyKey?:string}):Promise<OperationExecution<{stagedPaths:string[]}>>{const paths=guardedPaths(guard,ws,input.paths); return ops.execute({kind:"git_stage",idempotencyKey:input.idempotencyKey},async()=>{assertState(config,ws,input.expectedHead); git(ws,["add","--",...paths],config.maxOutputBytes); const selected=staged(config,ws).filter(p=>paths.includes(p)); return {stagedPaths:selected};},r=>({paths:r.stagedPaths,items:r.stagedPaths.length}));}
export async function gitCommit(config:CodexProConfig,_guard:PathGuard,ws:Workspace,ops:OperationManager,input:{message:string;expectedHead:string;expectedBranch:string;expectedStagedPaths:string[];idempotencyKey?:string}):Promise<OperationExecution<{commit:string;stagedPaths:string[]}>>{if(!input.message?.trim()||/[\r\n\0]/.test(input.message)||input.message.length>300)throw new CodexProError("commit message must be one line and at most 300 characters."); if(!REF.test(input.expectedBranch))throw new CodexProError("invalid expected branch."); return ops.execute({kind:"git_commit",idempotencyKey:input.idempotencyKey},async()=>{assertState(config,ws,input.expectedHead,input.expectedBranch); const current=staged(config,ws).sort(); const expected=[...new Set(input.expectedStagedPaths)].sort(); if(!current.length)throw new CodexProError("No staged changes to commit."); if(JSON.stringify(current)!==JSON.stringify(expected))throw new CodexProError(`Staged set changed; expected ${expected.join(", ")||"none"}, found ${current.join(", ")||"none"}.`); git(ws,["commit","-m",input.message,"--"],config.maxOutputBytes); return {commit:git(ws,["rev-parse","HEAD"],config.maxOutputBytes),stagedPaths:current};},r=>({paths:r.stagedPaths,items:r.stagedPaths.length,note:`commit ${r.commit.slice(0,12)}`}));}
export async function gitPush(config:CodexProConfig,_guard:PathGuard,ws:Workspace,ops:OperationManager,input:{remote:string;branch:string;expectedHead:string;expectedBranch:string;idempotencyKey?:string}):Promise<OperationExecution<{remote:string;branch:string;head:string}>>{if(!config.allowGitPush)throw new CodexProError("Git push is disabled. Set CODEXPRO_ALLOW_GIT_PUSH=1 to opt in."); if(!REF.test(input.remote)||!REF.test(input.branch)||!REF.test(input.expectedBranch))throw new CodexProError("invalid Git remote or branch."); return ops.execute({kind:"git_push",idempotencyKey:input.idempotencyKey},async()=>{const s=assertState(config,ws,input.expectedHead,input.expectedBranch); if(input.branch!==s.branch)throw new CodexProError("push branch must equal the checked-out expected branch."); git(ws,["push","--porcelain",input.remote,`${input.branch}:${input.branch}`],config.maxOutputBytes); return {remote:input.remote,branch:input.branch,head:s.head};},r=>({note:`pushed ${r.branch} to ${r.remote}`}));}
